DROP TABLE LAW_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE LAW_AUDIT
(
  DISPUTE_ID      NUMBER,
  ADJUSTED_TOTAL  VARCHAR2(30 BYTE),
  CLIENT_CODE     VARCHAR2(40 BYTE),
  CURTAIL_DATE    DATE,
  DISPUTE_AMT     VARCHAR2(30 BYTE),
  INVOICE_AMT     VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
