DROP TABLE SQA_TD_60 CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_60
(
  CONTRACTOR      VARCHAR2(255 BYTE),
  REPORT_SEGMENT  VARCHAR2(20 BYTE),
  COMPLETED_DT    DATE,
  LOANNUMBER      VARCHAR2(255 BYTE),
  ADD_1           VARCHAR2(255 BYTE),
  ADD_2           VARCHAR2(255 BYTE),
  CITY            VARCHAR2(255 BYTE),
  ST              VARCHAR2(2 BYTE),
  ZIP             VARCHAR2(15 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
